#!/usr/bin/env bash

if [ "$(command -v brew)" ]; then
	brew install \
		cmake \
		openssl \
		readline \
		sqlite3 \
		xz \
		tcl-tk \
		zlib
	if [ "$(command -v pyenv)" ]; then
		for version in 3.9 3.10 3.11; do
			if [[ $(pyenv versions) =~ $version ]]; then
				echo "$(date '+%Y-%m-%d %H:%M:%S'): Skipping Python $version..."
			else
				echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing Python $version..."
				pyenv install "$version":latest
			fi
		done
	fi
fi
