#!/usr/bin/env bash

if [ -x "$(command -v brew)" ]; then
	brew tap homebrew/cask-fonts
	brew install \
		mas \
		qemu \
		ruby \
		watch \
		zplug
	brew link -f --overwrite ruby # https://bit.ly/3UY3bcE
	brew install --cask \
		1password \
		cyberghost-vpn \
		dropbox \
		font-fira-code-nerd-font \
		iterm2 \
		multipass \
		postman \
		signal \
		spotify \
		telegram \
		whatsapp

	# virtualbox:
	# Error: Cask virtualbox depends on hardware architecture being one of
	# [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.

	# lunarvim
	brew install gnu-sed

	# python
	brew install \
		cmake \
		mysql \
		postgresql@15 \
		unixodbc
	brew services start postgresql@15
fi
