#!/usr/bin/env bash

if ! [ -x "$(command -v brew)" ]; then
	brew install \
		ruby \
		watch \
		zplug
	brew link -f --overwrite ruby # https://bit.ly/3UY3bcE
	brew install --cask \
		1password \
		cyberghost-vpn \
		dropbox \
		postman \
		signal \
		spotify \
		telegram

	# lunarvim
	brew install gnu-sed

	# python
	brew install \
		cmake \
		mysql \
		postgresql@15 \
		unixodbc
	brew services start postgresql@15
fi
