#!/usr/bin/env bash

if ! [ -x "$(command -v brew)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing 'brew'..."
	url=https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
	/bin/bash -c "$(curl -fsSL $url)"
	eval "$(/opt/homebrew/bin/brew shellenv)"
	brew install gcc
fi
