exclude: submodules/
repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-absolute-import
          - flake8-annotations
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-debugger
          - flake8-eradicate
          - flake8-executable
          - flake8-future-import
          - flake8-implicit-str-concat
          - flake8-mutable
          - flake8-print
          - flake8-pytest-style
          - flake8-simplify
          - flake8-string-format
          - flake8-unused-arguments
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.17.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: script-must-have-extension
        exclude: (.bash_profile|.bashrc)
      - id: script-must-not-have-extension
      - id: shfmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa
        additional_dependencies:
          - flake8-absolute-import
          - flake8-annotations
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-debugger
          - flake8-eradicate
          - flake8-executable
          - flake8-future-import
          - flake8-implicit-str-concat
          - flake8-mutable
          - flake8-print
          - flake8-pytest-style
          - flake8-simplify
          - flake8-string-format
          - flake8-unused-arguments
  - repo: meta
    hooks:
      - id: check-useless-excludes
