exclude: submodules/
repos:
  # fixers
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa
        additional_dependencies:
          - flake8-absolute-import
          - flake8-alphabetize
          - flake8-annotations
          - flake8-bandit
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-debugger
          - flake8-eradicate
          - flake8-executable
          - flake8-implicit-str-concat
          - flake8-length
          - flake8-mutable
          - flake8-no-pep420
          - flake8-pep3101
          - flake8-pie
          - flake8-print
          - flake8-pytest-style
          - flake8-simplify
          - flake8-string-format
          - flake8-type-checking
          - flake8-typing-imports
          - flake8-unused-arguments
          - flake8-use-fstring
          - flake8-variables-names
          - pep8-naming
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shfmt
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --remove-duplicate-keys,
            --remove-unused-variables,
          ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  # linters
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: script-must-have-extension
      - id: script-must-not-have-extension
  - repo: https://github.com/kumaraditya303/mirrors-pyright
    rev: v1.1.237
    hooks:
      - id: pyright
        exclude: dropbox.py|ipython/
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-absolute-import
          - flake8-alphabetize
          - flake8-annotations
          - flake8-bandit
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-debugger
          - flake8-eradicate
          - flake8-executable
          - flake8-implicit-str-concat
          - flake8-length
          - flake8-mutable
          - flake8-no-pep420
          - flake8-pep3101
          - flake8-pie
          - flake8-print
          - flake8-pytest-style
          - flake8-simplify
          - flake8-string-format
          - flake8-type-checking
          - flake8-typing-imports
          - flake8-unused-arguments
          - flake8-use-fstring
          - flake8-variables-names
          - pep8-naming
        exclude: dropbox.py
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
        args: [--enforce-all]
        exclude: fonts/
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: bash/(bashrc|bash_profile).sh
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: no-commit-to-branch
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
  - repo: meta
    hooks:
      - id: check-useless-excludes
