#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_DIR="submodules/dotbot"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/bin/dotbot" -d "${BASEDIR}" \
	--plugin-dir dotbot-apt \
	--plugin-dir dotbot-brew \
	-c apt.conf.yaml \
	-c install.conf.yaml \
	"${@}"
