# top-level
format = """
$time\
$username\
$hostname\
$localip\
$shlvl\
$directory\
\
$git_branch\
$git_state\
$git_status\
$git_commit\
$git_metrics\
\
$docker_context\
$package\
$container\
\
$buf$c$cmake$cobol$crystal$dart$deno$dotnet$elixir$elm$erlang$golang$haskell\
$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$perl$php$purescript$python$red\
$rlang$ruby$rust$scala$swift$terraform$vagrant$vlang$zig\
\
$memory_usage\
$sudo\
$cmd_duration\
\
\
\
$line_break\
\
\
\
$jobs\
$battery\
$status\
$shell\
$character"""

[cmd_duration]
format = "( [$duration]($style))"

[directory]
format = "( [$path]($style)[$read_only]($read_only_style))"
repo_root_format = "( [$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style))"
repo_root_style = "bold cyan"
truncation_length = 8
truncation_symbol = ".../"

[git_branch]
format = "( [$symbol$branch(:$remote_branch)]($style))"

[git_commit]
format = "( [$hash$tag]($style))"

[git_metrics]
disabled = false
format = "( [+$added]($added_style)[-$deleted]($deleted_style))"

[git_state]
format = "( [$state:($progress_current/$progress_total)]($style))"

[git_status]
format = "( [$conflicted]($style))( [$ahead]($style))( [$behind]($style))( [$diverged]($style))( [$up_to_date]($style))( [$untracked]($style))( [$stashed]($style))( [$modified]($style))( [$staged]($style))( [$renamed]($style))( [$deleted]($style))"
conflicted = "=$count"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕$count"
up_to_date = "$count"
untracked = "?$count"
stashed = "\\$$$count"
modified = "!$count"
staged = "+$count"
renamed = "»$count"
deleted = "✘$count"
ignore_submodules = true

[hostname]
format = "( [$hostname]($style))"

[localip]
disabled = false
format = "( [$localipv4]($style))"

[memory_usage]
disabled = false
format = "( [$symbol$ram(|$swap)]($style))"

[package]
format = "( [$symbol$version]($style))"
version_format = "$raw"

[shlvl]
disabled = false
format = "( [$symbol$shlvl]($style))"
symbol = "↕️"

[sudo]
format = "( [$symbol]($style))"
disabled = true

[time]
disabled = false
format = "[$time]($style)" # this is the first
time_format = "%I:%M:%S%P"

[username]
format = "( [$user]($style))"

# language-specific
[elm]
format = "( [$symbol$version]($style))"
style = "cyan"
version_format = "$raw"

[golang]
format = "( [$symbol$version]($style))"
style = "cyan"
version_format = "$raw"

[haskell]
format = "( [$symbol$version]($style))"
style = "purple"
version_format = "$raw"

[julia]
format = "( [$symbol$version]($style))"
style = "purple"
version_format = "$raw"

[kotlin]
format = "( [$symbol$version]($style))"
version_format = "$raw"
style = "blue"

[lua]
format = "( [$symbol$version]($style))"
style = "blue"
version_format = "$raw"

[nodejs]
disabled = true
format = "( [$symbol$version]($style))"
style = "green"
version_format = "$raw"

[python]
format = "( [$symbol$version]($style))"
style = "yellow"
version_format = "$raw"

[rust]
format = "( [$symbol$version]($style))"
style = "red"
version_format = "$raw"
