keybinds:
  unbind:
    - Ctrl: "g" # SwitchToMode: Locked
    - Ctrl: "p" # SwitchToMode: Pane
    - Ctrl: "n" # SwitchToMode: Resize
    - Ctrl: "t" # SwitchToMode: Tab
    - Ctrl: "s" # SwitchToMode: Scroll
    - Ctrl: "o" # SwitchToMode: Session
    - Ctrl: "h" # SwitchToMode: Move
    - Ctrl: "b" # SwitchToMode: Tmux
    - Ctrl: "q" # Quit
  normal:
    - action: [SwitchToMode: Locked]
      key: [Alt: "g"]
    - action: [SwitchToMode: Resize]
      key: [Alt: "r"]
    - action: [SwitchToMode: Pane]
      key: [Alt: "p"]
    - action: [SwitchToMode: Tab]
      key: [Alt: "t"]
    - action: [SwitchToMode: Scroll]
      key: [Alt: "s"]
    - action: [SwitchToMode: Session]
      key: [Alt: "o"]
    - action: [SwitchToMode: Move]
      key: [Alt: "m"]
  locked:
    - action: [SwitchToMode: Locked]
      key: [Alt: "g"]
  resize:
    - action: [SwitchToMode: Normal]
      key: [Char: "\n", Char: " ", Esc]
    - action: [SwitchToMode: Locked]
      key: [Alt: "g"]
    - action: [SwitchToMode: Pane]
      key: [Alt: "p"]
    - action: [SwitchToMode: Tab]
      key: [Alt: "t"]
    - action: [SwitchToMode: Scroll]
      key: [Alt: "s"]
    - action: [SwitchToMode: Session]
      key: [Alt: "o"]
    - action: [SwitchToMode: Move]
      key: [Alt: "m"]
  pane:
    - action: [SwitchToMode: Normal]
      key: [Char: "\n", Char: " ", Esc]
    - action: [SwitchToMode: Locked]
      key: [Alt: "g"]
    - action: [SwitchToMode: Resize]
      key: [Alt: "r"]
    - action: [SwitchToMode: Tab]
      key: [Alt: "t"]
    - action: [SwitchToMode: Scroll]
      key: [Alt: "s"]
    - action: [SwitchToMode: Session]
      key: [Alt: "o"]
    - action: [SwitchToMode: Move]
      key: [Alt: "m"]
  tab:
    - action: [SwitchToMode: Normal]
      key: [Char: "\n", Char: " ", Esc]
    - action: [SwitchToMode: Locked]
      key: [Alt: "g"]
    - action: [SwitchToMode: Resize]
      key: [Alt: "r"]
    - action: [SwitchToMode: Pane]
      key: [Alt: "p"]
    - action: [SwitchToMode: Scroll]
      key: [Alt: "s"]
    - action: [SwitchToMode: Session]
      key: [Alt: "o"]
    - action: [SwitchToMode: Move]
      key: [Alt: "m"]
  scroll:
    - action: [SwitchToMode: Normal]
      key: [Char: "\n", Char: " ", Esc]
    - action: [SwitchToMode: Locked]
      key: [Alt: "g"]
    - action: [SwitchToMode: Resize]
      key: [Alt: "r"]
    - action: [SwitchToMode: Pane]
      key: [Alt: "p"]
    - action: [SwitchToMode: Tab]
      key: [Alt: "t"]
    - action: [SwitchToMode: Session]
      key: [Alt: "o"]
    - action: [SwitchToMode: Move]
      key: [Alt: "m"]
  session:
    - action: [SwitchToMode: Normal]
      key: [Char: "\n", Char: " ", Esc]
    - action: [SwitchToMode: Locked]
      key: [Alt: "g"]
    - action: [SwitchToMode: Resize]
      key: [Alt: "r"]
    - action: [SwitchToMode: Pane]
      key: [Alt: "p"]
    - action: [SwitchToMode: Tab]
      key: [Alt: "t"]
    - action: [SwitchToMode: Session]
      key: [Alt: "o"]
    - action: [SwitchToMode: Move]
      key: [Alt: "m"]

copy_on_select: true
