#!/usr/bin/env bash

_PATH=/etc/dynuiuc/dynuiuc.conf
if
	[ "$HOSTNAME" == 'DW-PC' ] && ! [ -f "$_PATH" ]
then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Configuring 'dynu'..."
	url=https://www.dynu.com/support/downloadfile/31
	file="$(mktemp)"
	wget "$url" -qO "$file" && sudo dpkg -i "$file"
	rm "$file"
	sudo vim "$_PATH"
	systemctl enable dynuiuc.service
	systemctl start dynuiuc.service
else
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Skipping 'dynu'..."
fi
