#!/usr/bin/env bash

if ! [ -x "$(command -v brew)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing 'brew'..."
	sudo apt install -y curl
	url=https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
	sudo curl -sSf "$url" | bash
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
	sudo apt install -y build-essential
	brew install gcc
fi
