#!/usr/bin/env bash

sudo apt install -y \
	make \
	build-essential \
	curl \
	libbz2-dev \
	libffi-dev \
	liblzma-dev \
	libmysqlclient-dev \
	libncursesw5-dev \
	libpq-dev \
	libreadline-dev \
	libsqlite3-dev \
	libssl-dev \
	libxml2-dev \
	libxmlsec1-dev \
	llvm \
	python3-dev \
	python3-tk \
	tk-dev \
	unixodbc-dev \
	wget \
	xz-utils \
	zlib1g-dev
if [ "$(command -v pyenv)" ]; then
	for version in 3.9 3.10 3.11; do
		if [[ $(pyenv versions) =~ $version ]]; then
			echo "$(date '+%Y-%m-%d %H:%M:%S'): Skipping Python $version..."
		else
			echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing Python $version..."
			CC="$(brew --prefix gcc)/bin/gcc-12" pyenv install "$version":latest
		fi
	done
fi
