#!/usr/bin/env bash
# shellcheck source=/dev/null

_FILE=.env
if [ -z "$DUCKDNS_TOKEN" ] && [ -f "$_FILE" ]; then
	source "$_FILE"
fi

if [ -z "$DUCKDNS_TOKEN" ]; then
	echo 'Environment variable "DUCKDNS_TOKEN" is not set'
	exit 0
fi

domains=()
case "$OSTYPE" in
darwin*)
	domains+=(dw-mac)
	;;
linux*)
	domains+=(dw-pc)
	domains+=(part-time)
	;;
*)
	echo "Unsupported OS type: $OSTYPE"
	exit 0
	;;
esac

path_logs="${XDG_CACHE_HOME:-$HOME/.cache}/duckdns"
for domain in "${domains[@]}"; do
	url="https://www.duckdns.org/update?domains=$domain&token=$DUCKDNS_TOKEN&ip="
	path_log="$path_logs/$domain"
	echo url="$url" | curl -k -o "$path_log" -K -
done
