#!/usr/bin/env bash

# SSH key
./setup-ssh-keys

# clone dotfiles
./clone-dotfiles

# symlinks
(
	cd ../common || exit
	DOTBOT_CONFIG=dotbot.main.yaml ./run-dotbot
)
DOTBOT_CONFIG=dotbot.ubuntu.yaml ./run-dotbot

# apt
./install-apt-packages

# brew
./install-brew
./install-brew-packages
../common/install-brew-packages

# certbot
./install-certbot

# docker
./install-docker

# fzf
../common/setup-fzf

# lunarvim
(
	cd ../common || exit
	./install-lunarvim
)

# npm
../common/install-npm-packages

# pyenv
./install-pyenv-versions

# snap
./install-snap-packages
