#!/usr/bin/env bash

application=just

# parse options
while getopts 'f' option; do
	case "$option" in
	f) force=1 ;;
	?) echo "Unrecognized option: $option" ;;
	esac
done
shift "$((OPTIND - 1))"

# install app
if ! [ -x "$(command -v $application)" ] || [ -n "$force" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	url=https://just.systems/install.sh
	dest="$HOME/.local/bin"
	mkdir -p "$dest"
	curl --proto '=https' --tlsv1.2 -sSf "$url" | bash -s -- --to "$dest"
fi
