#!/usr/bin/env bash

application=shellcheck

# parse options
while getopts 'fl' option; do
	case "$option" in
	f) force=1 ;;
	?) echo "Unrecognized option: $option" ;;
	esac
done
shift "$((OPTIND - 1))"

# install app
app_path="$HOME/.local/bin/$application"
if ! [ -f "$app_path" ] || [ -n "$force" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	temp_dir="$(mktemp -d -t $application-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	(
		cd "$temp_dir" || exit
		api_url=https://api.github.com/repos/koalaman/shellcheck/releases/latest
		download_url=$(
			curl -s "$api_url" |
				grep browser_download_url |
				grep linux.x86_64 |
				cut -d : -f 2,3 |
				tr -d '[:blank:]' |
				tr -d \"
		)
		echo "$(date '+%Y-%m-%d %H:%M:%S'): Downloading $download_url..."
		wget -q "$download_url"
		filename="$(basename "$download_url")"
		tar -xf "$filename"
		trimmed="${filename//\.linux\.86_64.tar.xz/}"
		chmod u+x "$trimmed"
		app_path="$HOME/.local/bin/$application"
		mkdir -p "$(dirname "$app_path")"
		cp "$trimmed" "$app_path"
	)
	rm -r "$temp_dir"
fi
