#!/usr/bin/env bash

application=lvim

# parse options
while getopts 'fl' option; do
	case "$option" in
	f) force=1 ;;
	l) install_make=1 ;;
	?) echo "Unrecognized option: $option" ;;
	esac
done
shift "$((OPTIND - 1))"

# install app
if ! [ -x "$(command -v $application)" ] || [ -n "$force" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	if [ -n "$install_make" ]; then
		sudo apt -y install make
	fi
	dir_of_script=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	(
		cd "$dir_of_script" || exit
		./install-npm
		./install-rust
	)
	url=https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Downloading $url..."
	bash <(curl -s "$url") -s -- -y --no-install-dependencies
	(
		cd "$dir_of_script" || exit
		DOTBOT_CONFIG=post-lunarvim.yaml ./run-dotbot
	)
fi
