#!/usr/bin/env bash

application=zoxide

# install app
if ! [ -x "$(command -v $application)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	url=https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
	curl -sS "$url" | bash
fi
