#!/usr/bin/env bash

application=fzf

# parse options
while getopts 'ft' option; do
	case "$option" in
	f) force=1 ;;
	t) install_tree=1 ;;
	?) echo "Unrecognized option: $option" ;;
	esac
done
shift "$((OPTIND - 1))"

# install app
if ! [ -x "$(command -v $application)" ] || [ -n "$force" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	if [ -n "$install_tree" ]; then
		sudo apt -y install tree
	fi
	(
		cd "$HOME" || exit
		fzf_root=.fzf
		rm -rf "$fzf_root"
		git clone --depth 1 https://github.com/junegunn/fzf.git "$fzf_root"
		./"$fzf_root"/install --completion --key-bindings --xdg --no-update-rc
	)
fi
