#!/usr/bin/env bash

application=starship

# parse options
while getopts 'f' option; do
	case "$option" in
	f) force=1 ;;
	?) echo "Unrecognized option: $option" ;;
	esac
done
shift "$((OPTIND - 1))"

# install app
if ! [ -x "$(command -v $application)" ] || [ -n "$force" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	url=https://starship.rs/install.sh
	curl -sS "$url" | sh -s -- -b="$HOME/.local/bin" -y
fi
