#!/usr/bin/env bash

application=watchexec

# parse options
while getopts 'f' option; do
	case "$option" in
	f) force=1 ;;
	?) echo "Unrecognized option: $option" ;;
	esac
done
shift "$((OPTIND - 1))"

# install app
if ! [ -x "$(command -v $application)" ] || [ -n "$force" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	tempdir="$(mktemp -d -t $application-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	(
		cd "$tempdir" || exit
		api_url=https://api.github.com/repos/watchexec/watchexec/releases/latest
		download_url=$(
			curl -s "$api_url" |
				grep browser_download_url |
				grep x86_64-unknown-linux-gnu\.tar\.xz |
				grep -v \.b3 |
				grep -v \.sha256 |
				grep -v \.sha512 |
				cut -d : -f 2,3 |
				tr -d '[:blank:]' |
				tr -d \"
		)
		echo "$(date '+%Y-%m-%d %H:%M:%S'): Downloading $download_url..."
		wget -q "$download_url"
		filename="$(basename "$download_url")"
		tar -xf "$filename"
		trimmed="${filename//.tar.xz/}"
		cd "$trimmed" || exit
		app_path="$HOME/.local/bin/$application"
		mkdir -p "$(dirname "$app_path")"
		cp "$application" "$app_path"
		comp_path="$HOME/.local/completions/$application"
		mkdir -p "$(dirname "$comp_path")"
		cp -r completions "$comp_path"
	)
	rm -r "$tempdir"
fi
