#!/usr/bin/env bash

application=pyenv

# parse options
while getopts 'af' option; do
	case "$option" in
	a) install_apt=1 ;;
	f) force=1 ;;
	?) echo "Unrecognized option: $option" ;;
	esac
done
shift "$((OPTIND - 1))"

# install app
if ! [ -x "$(command -v $application)" ] || [ -n "$force" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	url=https://pyenv.run
	curl "$url" | bash
	if [ -n "$install_apt" ]; then
		sudo apt -y install \
			build-essential \
			curl \
			libbz2-dev \
			libffi-dev \
			liblzma-dev \
			libncursesw5-dev \
			libreadline-dev \
			libsqlite3-dev \
			libssl-dev \
			libxml2-dev \
			libxmlsec1-dev \
			tk-dev \
			xz-utils \
			zlib1g-dev
	fi
	for version in 3.9 3.10 3.11; do
		pyenv install "$version":latest
	done
fi
