#!/usr/bin/env bash

application=1password

# install app
if ! [ -x "$(command -v $application)" ]; then
	cd "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)" || exit
	./install-curl "$@"

	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	temp_dir="$(mktemp -d -t $application-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	cd "$temp_dir" || exit
	url=https://downloads.1password.com/linux/tar/stable/x86_64/1password-latest.tar.gz
	curl -sSO "$url"
	filename="$(basename "$url")"
	tar -xf "$filename"
	app_path=/opt/1Password
	sudo mkdir -p "$app_path"
	sudo mv 1password-*/* "$app_path"
	sudo "$app_path/after-install.sh"
	rm -r "$temp_dir"
fi
