#!/usr/bin/env bash

application=stylua

# install app
if ! [ -x "$(command -v $application)" ]; then
	cd "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)" || exit
	./install-curl "$@"

	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	temp_dir="$(mktemp -d -t $application-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	cd "$temp_dir" || exit
	api_url=https://api.github.com/repos/JohnnyMorganz/StyLua/releases/latest
	download_url=$(
		curl -s "$api_url" |
			grep browser_download_url |
			grep linux-x86_64 |
			cut -d : -f 2,3 |
			tr -d '[:blank:]' |
			tr -d \"
	)
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Downloading $download_url..."
	wget -q "$download_url"
	filename="$(basename "$download_url")"
	unzip "$filename"
	chmod u+x "$filename"
	app_path="$HOME/.local/bin/$application"
	mkdir -p "$(dirname "$app_path")"
	cp "$filename" "$app_path"
	rm -r "$temp_dir"
fi
