#!/usr/bin/env bash

if ! [ -x "$(command -v brew)" ]; then
	brew install \
		bat \
		black \
		bottom \
		cookiecutter \
		direnv \
		dust \
		exa \
		fd \
		ffmpeg \
		fzf \
		git-delta \
		htop \
		just \
		luacheck \
		neovim \
		node \
		pipx \
		pre-commit \
		prettier \
		pyenv \
		pyright \
		restic \
		ripgrep \
		ruff \
		rust \
		shellcheck \
		shfmt \
		starship \
		stylua \
		tmux \
		topgrade \
		watch \
		watchexec \
		yoannfleurydev/gitweb/gitweb \
		zoxide
fi
