#!/usr/bin/env bash

if [ "$(command -v pipx)" ]; then
	packages=(
		asciinema
		bump2version
	)
	for package in "${packages[@]}"; do
		if [[ $(pipx list --short) =~ $package ]]; then
			echo "$(date '+%Y-%m-%d %H:%M:%S'): Skipping '$package'..."
		else
			echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$package'..."
			pipx install "$package"
		fi
	done
fi
