#!/usr/bin/env bash

if [ -x "$(command -v brew)" ]; then
	brew tap homebrew/cask-fonts
	brew link -f --overwrite ruby # https://bit.ly/3UY3bcE
	brew install --cask \
		cyberghost-vpn \
		font-fira-code-nerd-font \
		iterm2 \
		postman \
		signal \
		spotify \
		telegram \
		whatsapp \
		zoom

	# lunarvim
	brew install gnu-sed

fi
