#!/usr/bin/env bash

if ! [ -x "$(command -v brew)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing 'brew'..."
	url=https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
	sudo curl -sSf "$url" | bash
	eval "$(/opt/homebrew/bin/brew shellenv)"
	brew install gcc
fi
