#!/usr/bin/env bash

if [ -x "$(command -v npm)" ]; then
	packages=(
		prettier-plugin-toml
	)
	for package in "${packages[@]}"; do
		if [[ $(npm list -global) =~ $package ]]; then
			echo "$(date '+%Y-%m-%d %H:%M:%S'): Skipping '$package'..."
		else
			echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$package'..."
			npm install -g "$package"
		fi
	done
fi
