#!/usr/bin/env bash

if [ -x "$(command -v brew)" ]; then
	brew tap homebrew/cask-fonts
	brew install \
		docker \
		mas \
		qemu \
		ruby \
		watch \
		zplug
	brew link -f --overwrite ruby # https://bit.ly/3UY3bcE
	brew install --cask \
		1password \
		cyberghost-vpn \
		dropbox \
		font-fira-code-nerd-font \
		iterm2 \
		multipass \
		postman \
		signal \
		spotify \
		telegram \
		whatsapp \
		zoom

	# lunarvim
	brew install gnu-sed

fi
