#!/usr/bin/env bash

# parse options
declare -a force=()
while getopts 'f' option; do
	case "$option" in
	f) force+=(-f) ;;
	?) echo "Unrecognized option: $option" ;;
	esac
done
shift "$((OPTIND - 1))"

# apt
sudo apt -y install \
	curl \
	git \
	neovim \
	tmux
sudo apt -y autoremove

# curl .../setup-ssh-keys | bash

# components
cd "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)" || exit
cd ../components || exit
DOTBOT_CONFIG=make-symlinks.yaml ./run-dotbot
DOTBOT_CONFIG=dotbot-bash.yaml ./run-dotbot
./install-1password -s
./install-bat -s
./install-bottom -s
./install-bump2version -s
./install-delta -s
./install-direnv -s
./install-docker -s
./install-dust -s
./install-exa -s
./install-fd -s
./install-fzf -s
./install-gitweb -s
./install-just -s
./install-lunarvim -s
./install-npm -s
./install-nvm -s
./install-pipx -s
./install-pyenv -s
./install-ripgrep -s
./install-rust -s
./install-sd -s
./install-shellcheck -s
./install-shfmt -s
./install-starship -s
./install-stylua -s
./install-watchexec -s
./install-zoxide -s
