#!/usr/bin/env bash

# parse options
declare -a force=()
while getopts 'f' option; do
	case "$option" in
	f) force+=(-f) ;;
	?) echo "Unrecognized option: $option" ;;
	esac
done
shift "$((OPTIND - 1))"

# components
dir_of_script=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
(
	cd "$dir_of_script" || exit
	cd .. || exit
	cd components || exit
	DOTBOT_CONFIG=make-symlinks.yaml ./run-dotbot
	DOTBOT_CONFIG=dotbot-bash.yaml ./run-dotbot
	./install-bat "${force[@]}"
	./install-bottom "${force[@]}"
	./install-delta "${force[@]}"
	./install-direnv "${force[@]}"
	./install-dust "${force[@]}"
	./install-exa "${force[@]}"
	./install-fd "${force[@]}"
	./install-fzf "${force[@]}"
	./install-gitweb "${force[@]}"
	./install-just "${force[@]}"
	./install-lunarvim "${force[@]}"
	./install-npm "${force[@]}"
	./install-nvm "${force[@]}"
	./install-ripgrep "${force[@]}"
	./install-rust "${force[@]}"
	./install-sd "${force[@]}"
	./install-starship "${force[@]}"
	./install-watchexec "${force[@]}"
	./install-zoxide "${force[@]}"
)
