#!/usr/bin/env bash

# components
cd "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)" || exit
cd ../components || exit
DOTBOT_CONFIG=make-symlinks.yaml ./run-dotbot
DOTBOT_CONFIG=dotbot-bash.yaml ./run-dotbot
./install-bat
./install-bottom
./install-bump2version
./install-delta
./install-direnv
./install-dust
./install-exa
./install-fd
./install-fzf
./install-gitweb
./install-just
./install-lunarvim
./install-npm
./install-nvm
./install-pipx
./install-pyenv
./install-ripgrep
./install-rust
./install-sd
./install-shellcheck
./install-shfmt
./install-starship
./install-stylua
./install-watchexec
./install-zoxide
