#!/usr/bin/env bash

if [ -x "$(command -v brew)" ]; then
	brew update
	brew upgrade
else
	sudo apt install -y curl

	# https://bit.ly/3rL7k6a
	echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
	sudo apt install -y build-essential
	brew install gcc
fi

# https://bit.ly/3Ox24gs
declare -a libs=(
	bat
	bottom
	broot
	direnv
	dust
	eth-p/software/bat-extras
	exa
	fd
	fselect
	fzf
	git-delta
	glow
	grex
	htop
	httpie
	hyperfine
	just
	neovim
	pandoc
	pgcli
	pipx
	pyright
	ranger
	ripgrep
	sd
	shellcheck
	shfmt
	sk
	starship
	stylua
	tokei
	tmux
	tre-command
	tree
	vim
	watchexec
	yoannfleurydev/gitweb/gitweb
	zoxide
	zsh
)
for lib in "${libs[@]}"; do
	brew ls --versions "$lib" || brew install "$lib"
done
