#!/usr/bin/env bash

# https://dockr.ly/3Mtr5Ye
sudo apt update -y
sudo apt install -y ca-certificates curl gnupg lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
	sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --yes
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |
	sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
sudo apt update -y
sudo apt install -y docker-ce docker-ce-cli containerd.io

# docker-compose
# https://dockr.ly/3MtQBMX
sudo curl -L \
	"https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
	-o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo curl -L \
	https://raw.githubusercontent.com/docker/compose/1.29.2/contrib/completion/bash/docker-compose \
	-o /etc/bash_completion.d/docker-compose

# permissions
# https://dockr.ly/3EIzMev
sudo groupadd docker
sudo usermod -aG docker "$USER"
newgrp docker
