#!/usr/bin/env bash

curl https://raw.githubusercontent.com/canha/golang-tools-install-script/master/goinstall.sh | bash

# go install github.com/posener/complete/gocomplete@latest
# gocomplete -install

# go install mvdan.cc/gofumpt@latest
