#!/usr/bin/env bash

# https://bit.ly/3Leza2A
# https://bit.ly/3xKilsj
# https://bit.ly/3ECcS8x
curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh | bash -s -- --no-install-dependencies

git checkout -- lvim/config.lua
