#!/usr/bin/env bash

# https://bit.ly/3xRVFXd
if ! sudo apt -qq list mongodb-org --installed | grep ^; then
	wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
	echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list >/dev/null
	sudo apt update -y
	sudo apt install -y mongodb-org
	sudo systemctl start mongod
	sudo systemctl enable mongod
fi
