#!/usr/bin/env bash

# https://bit.ly/3v7LoEz
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get -y install postgresql

# https://bit.ly/3vE0h0u
sudo apt-get update
sudo apt-get -y install libpq-dev
