#!/usr/bin/env bash

if ! grep -q WSL /proc/version; then
	declare -a libs=(
		signal-desktop
		spotify
		telegram-desktop
	)
	for lib in "${libs[@]}"; do
		sudo snap install "$lib"
	done

	declare -a libs=(
		flutter
		heroku
	)
	for lib in "${libs[@]}"; do
		sudo snap install --classic "$lib"
	done
fi
