#!/usr/bin/env bash

declare -a libs=(
	signal-desktop
	spotify
	telegram-desktop
)
for lib in "${libs[@]}"; do
	if ! snap list "$lib" | grep ^; then
		sudo snap install "$lib"
	fi
done

sudo snapp install --classic heroku
