#!/usr/bin/env bash

if ! grep -q WSL /proc/version; then
	declare -a libs=(
		signal-desktop
		spotify
		telegram-desktop
	)
	for lib in "${libs[@]}"; do
		if ! snap list "$lib" | grep ^; then
			sudo snap install "$lib"
		fi
	done

	declare -a libs=(
		go
		heroku
	)
	for lib in "${libs[@]}"; do
		if ! snap list "$lib" | grep ^; then
			sudo snap install --classic "$lib"
		fi
	done
fi
