#!/usr/bin/env bash

# direnv
sudo apt install -y direnv

# fzf
sudo apt install -y fzf

# just
curl -q 'https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg 1>/dev/null
echo "deb [signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/prebuilt-mpr.list
sudo apt update
sudo apt install -y just

# neovim
sudo apt install -y neovim

# starship
curl -sS https://starship.rs/install.sh | sh

# zoxide
apt install zoxide
