#!/usr/bin/env bash
# shellcheck source=/dev/null

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
components_dir="$(dirname "$script_dir")/components"
sudo apt -y install \
	bat \
	exa \
	ripgrep \
	tmux \
	vim
source "$components_dir/run-dotbot" make-symlinks.yaml
source "$components_dir/run-dotbot" dotbot-bash.yaml
source "$components_dir/setup-authorized-keys"
source "$components_dir/install-bottom"
source "$components_dir/install-fd"
source "$components_dir/install-fzf"
source "$components_dir/install-lunarvim"
source "$components_dir/install-starship"
source "$components_dir/install-watchexec"
source "$components_dir/install-zoxide"
