return {
	s("bp", { t("breakpoint()") }),
	s("fbebeartype", { t("from beartype import beartype") }),
	s("fdadataclass", { t("from dataclasses import dataclass") }),
	s("fhydata", { t("from hypothesis import data") }),
	s("fhygiven", { t("from hypothesis import given") }),
	s("fhyreproduce", { t("from hypothesis import reproduce_failure") }),
	s("flologger", { t("from loguru import logger") }),
	s("fpapath", { t("from pathlib import Path") }),
	s("fpddataframe", { t("from pandas import DataFrame") }),
	s("fpdreadpickle", { t("from pandas import read_pickle") }),
	s("fpdseries", { t("from pandas import Series") }),
	s("fpdtopickle", { t("from pandas import to_pickle") }),
	s("ftatabulate", { t("from tabluate import tabulate") }),
	s("fxadataarray", { t("from xarray import DataArray") }),
	s("fxadatasetl", { t("from xarray import Dataset") }),
	s("imdt", { t("import datetime as dt") }),
	s("imnp", { t("import numpy as np") }),
	s("impd", { t("import pandas as pd") }),
}
