#!/usr/bin/env bash
# shellcheck source=/dev/null

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ENV="$SCRIPT_DIR/.env"

if [ -f "$ENV" ]; then
	echo "Sourcing $ENV..."
	source "$ENV"

	declare -a PATHS_TO_BACKUP=("$PATH_DROPBOX" "$HOME/work")
	for PATH_TO_BACKUP in "${PATHS_TO_BACKUP[@]}"; do
		if [ -d "$PATH_TO_BACKUP" ]; then
			echo "Backing up $PATH_TO_BACKUP..."
			restic backup "$PATH_TO_BACKUP"
		else
			echo "Unable to find $PATH_TO_BACKUP; skipping..."
		fi
	done
else
	echo "Unable to find $ENV; exiting..."
fi
