#!/usr/bin/env bash
# shellcheck source=/dev/null

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ENV="$SCRIPT_DIR/.env"

if [ -f "$ENV" ]; then
	echo "Sourcing $ENV..."
	restic -r "$RESTIC_REPOSITORY" init
else
	echo "Unable to find $ENV; exiting..."
fi
