#!/usr/bin/env bash
# shellcheck source=/dev/null

# SSH key & dotfiles
temp_dir="$(mktemp -d -t dotfiles-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
(
	cd "$temp_dir" || exit
	sudo apt -y install git
	git clone https://github.com/dycw/dotfiles.git
	source "dotfiles/install/components/setup-ssh-key-and-clone-dotfiles"
)
rm -rf "$temp_dir"

# components
components_dir="$HOME/dotfiles/install/components"
sudo apt -y install \
	bat \
	exa \
	fd-find \
	ripgrep \
	shellcheck \
	tmux
source "$components_dir/install-black"
source "$components_dir/install-bottom"
source "$components_dir/install-bump2version"
source "$components_dir/install-delta"
source "$components_dir/install-direnv"
source "$components_dir/install-dust"
source "$components_dir/install-fzf"
source "$components_dir/install-gitweb"
source "$components_dir/install-just"
source "$components_dir/install-lunarvim"
source "$components_dir/install-pre-commit"
source "$components_dir/install-ruff"
source "$components_dir/install-rust"
source "$components_dir/install-sd"
source "$components_dir/install-shfmt"
source "$components_dir/install-starship"
source "$components_dir/install-stylua"
source "$components_dir/install-watchexec"
source "$components_dir/install-zoxide"
