#!/usr/bin/env bash
# shellcheck source=/dev/null

# clone dotfiles
sudo apt -y install curl
url=https://raw.githubusercontent.com/dycw/dotfiles/master/install/components/clone-dotfiles
# shellcheck source=/dev/null
source <(curl -fsS "$url")

# components
components_dir="$HOME/dotfiles/install/components" # cannot use usual `script_dir` given `curl`
sudo apt -y install \
	bat \
	exa \
	ripgrep \
	shellcheck \
	tmux
# source "$components_dir/install-1password"
source "$components_dir/install-black"
source "$components_dir/install-bottom"
source "$components_dir/install-bump2version"
source "$components_dir/install-delta"
source "$components_dir/install-direnv"
source "$components_dir/install-docker"
source "$components_dir/install-dust"
source "$components_dir/install-fd"
source "$components_dir/install-fzf"
source "$components_dir/install-gitweb"
source "$components_dir/install-just"
source "$components_dir/install-lunarvim"
source "$components_dir/install-pre-commit"
source "$components_dir/install-ruff"
source "$components_dir/install-rust"
source "$components_dir/install-sd"
source "$components_dir/install-shfmt"
source "$components_dir/install-starship"
source "$components_dir/install-stylua"
source "$components_dir/install-watchexec"
source "$components_dir/install-zoxide"
source "$components_dir/run-dotbot" make-symlinks.yaml
source "$components_dir/run-dotbot" dotbot-bash.yaml
