#!/usr/bin/env bash
# shellcheck source=/dev/null

# SSH key & dotfiles
sudo apt -y install curl
url=https://github.com/dycw/dotfiles/raw/master/install/components/setup-ssh-key-and-clone-dotfiles
url=https://raw.githubusercontent.com/dycw/dotfiles/dev/install/components/setup-ssh-key-and-clone-dotfiles
echo hi
curl -Sfs --proto '=https' --tlsv1.2 "$url" | bash
echo bye

# components
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
components_dir="$script_dir/components"
sudo apt -y install \
	bat \
	exa \
	fd-find \
	ripgrep \
	shellcheck
source "$components_dir/install-black"
source "$components_dir/install-bottom"
source "$components_dir/install-bump2version"
source "$components_dir/install-delta"
source "$components_dir/install-direnv"
source "$components_dir/install-dust"
source "$components_dir/install-fzf"
source "$components_dir/install-gitweb"
source "$components_dir/install-just"
source "$components_dir/install-lunarvim"
source "$components_dir/install-pre-commit"
source "$components_dir/install-ruff"
source "$components_dir/install-rust"
source "$components_dir/install-sd"
source "$components_dir/install-shfmt"
source "$components_dir/install-starship"
source "$components_dir/install-stylua"
source "$components_dir/install-watchexec"
source "$components_dir/install-zoxide"
