#!/usr/bin/env bash
# shellcheck source=/dev/null

# clone dotfiles
sudo apt -y install curl
url=https://raw.githubusercontent.com/dycw/dotfiles/master/install/components/clone-dotfiles
source <(curl -fsLS "$url")

# groups/components
install_dir="$HOME/dotfiles/install" # cannot use usual `script_dir` given `curl`
source "$install_dir/groups/minimal"
