#!/usr/bin/env bash
# shellcheck source=/dev/null

# clone dotfiles
sudo apt -y install curl
url=https://raw.githubusercontent.com/dycw/dotfiles/master/install/components/clone-dotfiles
source <(curl -fsLS "$url")

# groups/components
install_dir="$HOME/dotfiles/install" # cannot use usual `script_dir` given `curl`
components_dir="$install_dir/components"
sudo apt -y install \
	ruby-dev \
	shellcheck
source "$install_dir/groups/minimal"
source "$components_dir/install-certbot"
source "$components_dir/install-stylua"
