#!/usr/bin/env zsh

# preamble
files=(
  "$HOME/dotfiles/sh/source-all-files.sh"
  "$HOME/.zshrc.local"
)
for file in "${files[@]}"; do
if [ -f "$file" ]; then
	source "$file"
fi
done


# ---- rest -------------------------------------------------------------------

# completions
# to be implemented
# & pyenv




# zsh
alias zshrc='$EDITOR "$HOME/.zshrc"'
export HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/history"
