#!/usr/bin/env zsh

# preamble
files=(
  "$HOME/dotfiles/sh/source-all-files.sh"
  "$HOME/.zshrc.local"
)
for file in "${files[@]}"; do
if [ -f "$file" ]; then
	source "$file"
fi
done

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/derek/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/derek/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/derek/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/derek/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
