-- luacheck: ignore 113
-- luacheck: ignore 142

return {
	s("bp", { t("breakpoint()") }),
	s("fbebeartype", { t("from beartype import beartype") }),
	s("fdadataclass", { t("from dataclasses import dataclass") }),
	s("fdafield", { t("from dataclasses import field") }),
	s("fdafields", { t("from dataclasses import fields") }),
	s("fdareplace", { t("from dataclasses import replace") }),
	s("fenauto", { t("from enum import auto") }),
	s("fenenum", { t("from enum import Enum") }),
	s("fhyassume", { t("from hypothesis import assume") }),
	s("fhygiven", { t("from hypothesis import given") }),
	s("fhyreproduce", { t("from hypothesis import reproduce_failure") }),
	s("fhysettings", { t("from hypothesis import settings") }),
	s("fhystdata", { t("from hypothesis.strategies import data") }),
	s("fitrepeat", { t("from itertools import repeat") }),
	s("fitzipequal", { t("from itertools import zip_equal") }),
	s("flologger", { t("from loguru import logger") }),
	s("fnparange", { t("from numpy import arange") }),
	s("fnparray", { t("from numpy import array") }),
	s("fnpisfinite", { t("from numpy import isfinite") }),
	s("fnpisnan", { t("from numpy import isnan") }),
	s("fnpnan", { t("from numpy import nan") }),
	s("fnpndarray", { t("from numpy import ndarray") }),
	s("fnpones", { t("from numpy import ones") }),
	s("fnponeslike", { t("from numpy import ones_like") }),
	s("fnptyndarray", { t("from numpy.typing import NDArray") }),
	s("fnpzeros", { t("from numpy import zeros") }),
	s("fnpzeroslike", { t("from numpy import zeros_like") }),
	s("fpapath", { t("from pathlib import Path") }),
	s("fpddataframe", { t("from pandas import DataFrame") }),
	s("fpdreadpickle", { t("from pandas import read_pickle") }),
	s("fpdseries", { t("from pandas import Series") }),
	s("fpdtopickle", { t("from pandas import to_pickle") }),
	s("fpppprint", { t("from pprint import pprint") }),
	s("fpymark", { t("from pytest import mark") }),
	s("fpyparam", { t("from pytest import param") }),
	s("fpyraises", { t("from pytest import raises") }),
	s("fresearch", { t("from re import search") }),
	s("ftatabulate", { t("from tabluate import tabulate") }),
	s("ftyannotated", { t("from typing import Annotated") }),
	s("ftyany", { t("from typing import Any") }),
	s("ftycast", { t("from typing import cast") }),
	s("ftyiterable", { t("from typing import Iterable") }),
	s("ftyiterator", { t("from typing import Iterator") }),
	s("ftyoptional", { t("from typing import Optional") }),
	s("ftyunion", { t("from typing import Union") }),
	s("fxadataarray", { t("from xarray import DataArray") }),
	s("fxadatasetl", { t("from xarray import Dataset") }),
	s("imdt", { t("import datetime as dt") }),
	s("imnp", { t("import numpy as np") }),
	s("impd", { t("import pandas as pd") }),
}
