#!/usr/bin/env bash

_root=/etc/letsencrypt/
sudo find "$_root" -name '*.pem' -print0 -type f | while IFS= read -r -d '' _file; do
	echo "Found _file: '$_file'"
	sudo chgrp letsencrypt "$_file"
	sudo chmod g+r "$_file"
done
sudo find "$_root" -print0 -type d | while IFS= read -r -d '' _file; do
	echo "Found directory: '$_file'"
	sudo chgrp letsencrypt "$_file"
	sudo chmod g+rx "$_file"
done
