#!/usr/bin/env bash

root=/etc/letsencrypt/
sudo find "$root" -name '*.pem' -print0 -type f | while IFS= read -r -d '' file; do
	echo "Found file: '$file'"
	sudo chgrp letsencrypt "$file"
	sudo chmod g+r "$file"
done
sudo find "$root" -print0 -type d | while IFS= read -r -d '' file; do
	echo "Found directory: '$file'"
	sudo chgrp letsencrypt "$file"
	sudo chmod g+rx "$file"
done
