#!/usr/bin/env bash

sudo apt -y install curl
url=https://raw.githubusercontent.com/dycw/dotfiles/master/install/components/setup-ssh-key
# shellcheck source=/dev/null
source <(curl -fsLS "$url")

dotfiles="$HOME/dotfiles"
if [ -d "$dotfiles" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Updating dotfiles..."
	cd "$dotfiles" || exit
	git checkout master
	git pull
else
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Cloning dotfiles..."
	sudo apt -y install git
	(
		cd "$(dirname "$dotfiles")" || exit
		git clone --recurse-submodules git@github.com:dycw/dotfiles.git
	)
fi
