#!/usr/bin/env bash

app="$1"
if ! [ -x "$(command -v "$app")" ]; then
	script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	temp_dir="$(mktemp -d -t "$app"-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	(
		cd "$temp_dir" || exit
		source "$script_dir/download-from-github" "${@:2}"
		sudo dpkg -i ./*.deb
	)
	rm -rf "$temp_dir"
fi
