#!/usr/bin/env bash

if ! [ -x "$(command -v lvim)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing lunarvim..."
	sudo apt -y install curl make
	script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	source "$script_dir/install-neovim"
	source "$script_dir/install-npm"
	source "$script_dir/install-rust"
	url=https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh
	bash <(curl -s "$url") -s -- -y --no-install-dependencies
	source "$script_dir/run-dotbot" post-lunarvim.yaml
	lvim +LvimUpdate +q
fi
