#!/usr/bin/env bash

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$script_dir/download-and-install-deb-from-github" \
	watchexec watchexec watchexec x86_64-unknown-linux.gnu.deb .b3 .sha256 .sha512
