#!/usr/bin/env bash

if ! [ -x "$(command -v lvim)" ]; then
	sudo apt -y install curl make
	script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	source "$script_dir/install-neovim"
	source "$script_dir/install-npm"
	source "$script_dir/install-rust"
	url=https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh
	bash <(curl -s "$url") -s -- -y --no-install-dependencies
	DOTBOT_CONFIG=post-lunarvim.yaml "$script_dir/run-dotbot"
	lvim +LvimUpdate +q
fi
