#!/usr/bin/env bash

application=cargo

# install app
if ! [ -x "$(command -v $application)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	url=https://sh.rustup.rs
	curl --proto '=https' --tlsv1.2 -sSf "$url" | sh -s -- -y --no-modify-path
fi
