#!/usr/bin/env bash

if ! [ -x "$(command -v pipx)" ]; then
	script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	source "$script_dir/install-python-311"

	venv_path="$HOME/.local/bin/pipx_venv"
	mkdir -p "$venv_path"
	(
		cd "$venv_path" || exit
		PYENV_VERSION=3.11 python -m venv .venv
		# shellcheck source=/dev/null
		source .venv/bin/activate
		pip install pipx
		ln -s "$venv_path/.venv/bin/pipx" "$HOME/.local/bin/pipx"
	)
fi
