#!/usr/bin/env bash

application=pyenv

# parse options
while getopts 's' option; do
	case "$option" in
	s) has_sudo=1 ;;
	?) echo "Unrecognized option: $option" ;;
	esac
done

# install app
if ! [ -x "$(command -v $application)" ]; then
	cd "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)" || exit
	./install-curl "$@"

	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	url=https://pyenv.run
	curl "$url" | bash
	if [ -n "$has_sudo" ]; then
		sudo apt -y install \
			build-essential \
			curl \
			libbz2-dev \
			libffi-dev \
			liblzma-dev \
			libncursesw5-dev \
			libreadline-dev \
			libsqlite3-dev \
			libssl-dev \
			libxml2-dev \
			libxmlsec1-dev \
			tk-dev \
			xz-utils \
			zlib1g-dev
	fi
	for version in 3.9 3.10 3.11; do
		pyenv install "${version}:latest"
	done
fi
