#!/usr/bin/env bash

if ! [ -x "$(command -v nvim)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing neovim..."
	sudo apt -y install libfuse2
	script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	temp_dir="$(mktemp -d -t nvim-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	(
		cd "$temp_dir" || exit
		source "$script_dir/download-from-github" \
			neovim neovim appimage sha256sum zsync
		mv ./*appimage* nvim
		chmod u+x nvim
		bin_dir="$HOME/.local/bin/"
		mkdir -p "$bin_dir"
		mv nvim "$bin_dir/"
	)
	rm -rf "$temp_dir"
fi
