#!/usr/bin/env bash

application=curl

# parse options
while getopts 's' option; do
	case "$option" in
	s) has_sudo=1 ;;
	?) echo "Unrecognized option: $option" ;;
	esac
done

# install app
if ! [ -x "$(command -v $application)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	if [ -n "$has_sudo" ]; then
		sudo apt -y install "$application"
	fi
fi
