#!/usr/bin/env bash

export XDG_CONFIG_HOME="$HOME/.config"
export NVM_DIR="$XDG_CONFIG_HOME/nvm"
if ! [ -d "$NVM_DIR" ]; then
	sudo apt -y install curl
	url=https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
	curl -o- "$url" | bash
	# shellcheck source=/dev/null
	source "$NVM_DIR/nvm.sh"
fi
