#!/usr/bin/env bash

if [ -x "$(command -v gitweb)" ]; then
	script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	temp_dir="$(mktemp -d -t gitweb-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	(
		cd "$temp_dir" || exit
		source "$script_dir/download-from-github" yoannfleurydev gitweb linux
		ls -al
		mv ./*gitweb* gitweb
		chmod u+x gitweb
		bin_dir="$HOME/.local/bin/"
		mkdir -p "$bin_dir"
		mv shfmt "$bin_dir/"

		# Ubuntu:
		# ./gitweb: error while loading shared libraries: libssl.so.1.1: cannot
		# open shared object file: No such file or directory
		# https://bit.ly/3NcMJ6x
		echo "deb http://security.ubuntu.com/ubuntu focal-security main" |
			sudo tee /etc/apt/sources.list.d/focal-security.list
		sudo apt -y update
		sudo apt -y install libssl1.1
	)
	rm -rf "$temp_dir"
fi
