#!/usr/bin/env bash

if ! [ -x "$(command -v cargo)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing rust..."
	sudo apt -y install curl
	url=https://sh.rustup.rs
	curl --proto '=https' --tlsv1.2 -sSf "$url" | sh -s -- -y --no-modify-path
	# shellcheck source=/dev/null
	source "$HOME/.cargo/env"
fi
