#!/usr/bin/env bash

if ! [ -x "$(command -v sd)" ]; then
	script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	temp_dir="$(mktemp -d -t shfmt-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	(
		cd "$temp_dir" || exit
		source "$script_dir/download-from-github" chmln sd x86_64-unknown-linux-gnu
		mv ./*sd* sd
		chmod u+x sd
		ls -al
		bin_dir="$HOME/.local/bin/"
		mkdir -p "$bin_dir"
		mv sd "$bin_dir/"
	)
	rm -rf "$temp_dir"
fi
