#!/usr/bin/env bash

if ! [ -x "$(command -v 1password)" ]; then
	temp_dir="$(mktemp -d -t 1password-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	(
		cd "$temp_dir" || exit
		url=https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
		wget "$url"
		sudo dpkg -i ./*.deb
	)
	rm -rf "$temp_dir"
fi
