#!/usr/bin/env bash

if ! [ -x "$(command -v stylua)" ]; then
	script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	temp_dir="$(mktemp -d -t shfmt-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	(
		cd "$temp_dir" || exit
		source "$script_dir/download-from-github" JohnnyMorganz StyLua linux-x86_64
		unzip ./*.zip
		chmod u+x stylua
		bin_dir="$HOME/.local/bin/"
		mkdir -p "$bin_dir"
		mv stylua "$bin_dir/"
	)
	rm -rf "$temp_dir"
fi
