#!/usr/bin/env bash

if ! [ -x "$(command -v shfmt)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing shfmt..."
	script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	temp_dir="$(mktemp -d -t shfmt-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	(
		cd "$temp_dir" || exit
		source "$script_dir/download-from-github" mvdan sh linux_386
		mv ./*linux_386* shfmt
		chmod u+x shfmt
		bin_dir="$HOME/.local/bin/"
		mkdir -p "$bin_dir"
		mv shfmt "$bin_dir/"
	)
	rm -rf "$temp_dir"
fi
