#!/usr/bin/env bash

application=fzf

# install app
if ! [ -x "$(command -v $application)" ]; then
	cd "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)" || exit
	./install-git "$@"
	./install-tree "$@"

	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing '$application'..."
	cd "$HOME" || exit
	fzf_root=.fzf
	rm -rf "$fzf_root"
	git clone --depth 1 https://github.com/junegunn/fzf.git "$fzf_root"
	./"$fzf_root"/install --completion --key-bindings --xdg --no-update-rc
fi
