#!/usr/bin/env bash

if ! [ -x "$(command -v pyenv)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing pyenv..."
	sudo apt -y install \
		build-essential \
		curl \
		libbz2-dev \
		libffi-dev \
		liblzma-dev \
		libncursesw5-dev \
		libreadline-dev \
		libsqlite3-dev \
		libssl-dev \
		libxml2-dev \
		libxmlsec1-dev \
		tk-dev \
		xz-utils \
		zlib1g-dev
	url=https://pyenv.run
	curl "$url" | bash
	export PYENV_ROOT="$HOME/.pyenv"
	if ! [ -x "$(command -v pyenv)" ]; then
		export PATH="$PYENV_ROOT/bin:${PATH:+:$PATH}"
	fi
	eval "$(pyenv init -)"
fi
