#!/usr/bin/env bash

version="$1"
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$script_dir/install-pyenv"

if ! ("$(pyenv versions)" | grep "$version") >/dev/null; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing Python $version..."
	pyenv install "$version:latest"
fi
