#!/usr/bin/env bash

app_path="$HOME/.local/bin/nvim"
if ! [ -f "$app_path" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing neovim..."
	sudo apt -y install libfuse2
	script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	temp_dir="$(mktemp -d -t nvim-"$(date +%Y%m%d-%H%M%S)"-XXXXXXXX)"
	(
		cd "$temp_dir" || exit
		source "$script_dir/download-from-github" \
			neovim neovim appimage sha256sum zsync
		mv ./*appimage* nvim
		chmod u+x nvim
		mkdir -p "$(dirname "$app_path")"
		cp nvim "$app_path"
	)
	rm -rf "$temp_dir"
fi
