#!/usr/bin/env bash

if ! [ -x "$(command -v fzf)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing fzf..."
	(
		cd "$HOME" || exit
		git clone --depth 1 https://github.com/junegunn/fzf.git
		./install --xdg --key-bindings --completion --no-update-rc --no-fish
	)
fi
