#!/usr/bin/env bash
# shellcheck source=/dev/null

application=npm

# install app
if ! [ -x "$(command -v $application)" ]; then
	cd "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)" || exit
	./install-nvm "$@"

	source "$NVM_DIR/nvm.sh"
	nvm install --lts
fi
