#!/usr/bin/env bash

if ! [ -x "$(command -v npm)" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Installing npm..."
	script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
	source "$script_dir/install-nvm"
	nvm install --lts
fi
