#!/usr/bin/env bash

set -e

CONFIG="$1"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

(
	cd "$BASEDIR" || exit
	git -C dotbot submodule sync --quiet --recursive
	git submodule update --init --recursive dotbot
)

"$BASEDIR/dotbot/bin/dotbot" -d "$BASEDIR" -c "$CONFIG" "${@:2}"
