#!/usr/bin/env bash

path_ssh_key="$HOME/.ssh/id_rsa"
if ! [ -f "$path_ssh_key" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Setting up SSH key..."
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Please copy the private key for this machine ($HOSTNAME)"
	echo "$(date '+%Y-%m-%d %H:%M:%S'): You may wish to sign in at: https://my.1password.com/signin"
	read </dev/tty -p "Press 'y' to continue... " -n 1 -r
	echo
	if ! [[ "$REPLY" =~ ^[Yy]$ ]]; then
		echo "$(date '+%Y-%m-%d %H:%M:%S'): Exiting..."
		exit 0
	fi
	mkdir -p "$(dirname "$path_ssh_key")"
	sudo apt -y install xsel
	xsel -b >>"$path_ssh_key"
	chmod g-rwx,o-rwx "$path_ssh_key"
fi
