#!/usr/bin/env bash
# shellcheck source=/dev/null

# preamble
files=(
	"$HOME/dotfiles/sh/source-all-files.sh"
	"$HOME/.bashrc.local"
)
for file in "${files[@]}"; do
	if [ -f "$file" ]; then
		source "$file"
	fi
done

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
