#!/usr/bin/env bash
# shellcheck source=/dev/null

# preamble
files=(
	"$HOME/dotfiles/sh/source-all-files.sh"
	"$HOME/.bashrc.local"
)
for file in "${files[@]}"; do
	if [ -f "$file" ]; then
		source "$file"
	fi
done
