#!/usr/bin/env bash
# shellcheck source=/dev/null

# preamble
files=(
	"$HOME/dotfiles/sh/source-all-files.sh"
	"$HOME/.bashrc.local"
)
for file in "${files[@]}"; do
	if [ -f "$file" ]; then
		source "$file"
	fi
done

# fzf-tab-completion
if [ -x "$(command -v fzf)" ]; then
	_FILE="$_PATH_DOTFILES/submodules/fzf-tab-completion/bash/fzf-bash-completion.sh"
	if [ -f "$_FILE" ]; then
		source "$_FILE"
		bind -x '"\t": fzf_bash_completion'
	fi
fi
